accounts/urls.py
from django.urls import path
from .views import sign_in , sign_up , sign_out



app_name = 'accounts'


urlpatterns = [
	path('signin/' , sign_in , name = 'sign_in'),
	path('signup/', sign_up , name = 'sign_up'),
	path('signout/', sign_out, name = 'sign_out')
	]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/' , include('sonicresult.urls')),
    path('accounts/', include('accounts.urls')),
    path('credit/' , include('credit.urls')),
    path('' , include('home.urls'))
]

credit/urls.py
from django.urls import path
from .views import show_user_credit , increase_user_credit



app_name = 'credit'


urlpatterns = [
	path('', show_user_credit , name = 'show_user_credit'),
	path('increase_credit/', increase_user_credit , name = 'increase_user_credit' )
]

home/urls.py
from django.urls import path
from .views import home

app_name = 'home'



urlpatterns = [
	path('' , home , name = 'home')
]

sonicresult/urls.py
from django.urls import path
from .views import ResultView , SearchArticleView

app_name = 'sonicresult'


urlpatterns=[
    path('', SearchArticleView.as_view() , name = 'search_form'),
    path('result/', ResultView.as_view() , name = 'result'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser , PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from .managers import CustomUserManager
# Create your models here.



class CustomUser(AbstractBaseUser , PermissionsMixin):
	email = models.EmailField(_('email address'), unique = True)
	is_staff = models.BooleanField(default = False)
	is_active = models.BooleanField(default = True)
	date_joined = models.DateTimeField(default = timezone.now)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []


	objects = CustomUserManager()

	def __str__(self):
		return self.email

credit/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.


class UserCredit(models.Model):
	user = models.OneToOneField(CustomUser , on_delete=models.CASCADE)
	amount_credit = models.PositiveIntegerField(default = 0)


		

home/models.py
from django.db import models

# Create your models here.

sonicresult/models.py
from django.db import models
from accounts.models import CustomUser
from .services import main


# Create your models here.


class AiData(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    to_ai = models.TextField()
    from_ai = models.TextField()

    def save(self , *args , **kwargs):
        self.from_ai = main(self.to_ai)
        super(AiData, self).save(*args,**kwargs)
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm , UserChangeForm
from django.utils.translation import gettext_lazy as _
from django import forms
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
	class Meta:
		model = CustomUser
		fields = ('email',)


class CustomUserChangeForm(UserChangeForm):

	class Meta:
		model = CustomUser
		fields = ('email',)



class SignInForm(forms.Form):

	email = forms.EmailField()
	password = forms.CharField(label= _('password') , widget = forms.PasswordInput)

credit/forms.py
from django.forms import ModelForm
from .models import UserCredit



class IncreaseCreditForm(ModelForm):

	class Meta:
		model = UserCredit
		fields = ('amount_credit',)

sonicresult/forms.py
from django.forms import ModelForm
from .services import main
from .models import AiData


class SearchArticleForm(ModelForm):
    class Meta:
        model = AiData
        fields = ('to_ai',)

    def send_to_ai(self):
        main(self.data['to_ai'])

accounts/views.py
from django.shortcuts import render , redirect
from .forms import CustomUserCreationForm , SignInForm
from django.contrib.auth import authenticate , login , logout
from django.contrib import messages
# Create your views here.



def sign_in(request):
	if not request.user.is_authenticated:
	
		if request.method == "POST":
			email = request.POST['email']
			password = request.POST['password']
			user = authenticate(request , email = email , password = password)
			if user is not None :
				login(request , user)
				messages.success(request , f'Welcome {email}')
				return redirect('home:home')
	
		else:
			form = SignInForm()
		context = {
			'form' : form
		}
		return render(request , 'accounts/sign_in.html',context)
	else:
		return redirect('home:home')

def sign_up(request):
	if not request.user.is_authenticated:

		if request.method == 'POST':
			form = CustomUserCreationForm(request.POST)
			if form.is_valid:
				user = form.save()
				login(request , user)
				return redirect('home:home')
		else:
			form = CustomUserCreationForm()
	
		context = {
			'form':form
		}
		return render(request , 'accounts/sign_up.html' , context)
	else:
		return redirect('home:home')

def sign_out(request):
	logout(request)
	return redirect('home:home')

credit/views.py
from django.shortcuts import render ,redirect
from .models import UserCredit
from accounts.models import CustomUser
from .forms import IncreaseCreditForm

# Create your views here.



def show_user_credit(request):
	if request.user.is_authenticated:
		user = CustomUser.objects.filter(email = request.user).values().get()
		user_id = user['id']
		credit =  UserCredit.objects.filter(user_id = user_id).get()
		context = {
			'user_credit' : credit
		}
		return render(request , 'credit/show_user_credit.html' , context)


def increase_user_credit(request):
	if request.user.is_authenticated:
		user = request.user.usercredit
		if request.method == 'POST':
			form = IncreaseCreditForm(request.POST ,instance=user)
			if form.is_valid():
				form.save()
				
			return redirect('home:home')
		else:
			form = IncreaseCreditForm()
			context = {
				'form' : form
			}
			return render(request , 'credit/increase_user_credit.html' , context)

	

home/views.py
from django.shortcuts import render

# Create your views here.



def home (request):

	return render(request , 'home/index.html')

sonicresult/views.py
from django.views.generic import TemplateView, FormView
from django.urls import reverse_lazy
from .models import AiData
from .forms import SearchArticleForm
from accounts.models import CustomUser

# Create your views here

class SearchArticleView(FormView):
    template_name = 'sonicresult/search_article.html'
    form_class = SearchArticleForm
    success_url = reverse_lazy('sonicresult:result')

    def form_valid(self, form):
        search = form.save(commit=False)
        search.user = CustomUser.objects.get(email=self.request.user)
        form.save()
        return super().form_valid(form)


class ResultView(TemplateView):
    template_name = 'sonicresult/result.html'

    def get_context_data(self, **kwargs):
        context = {
            'result': AiData.objects.latest('pk')

        }
        return context

templates/accounts/sign_in.html
{% extends 'home/base.html' %}


{% block title %}
	<title>ورود</title>
{% endblock %}



{% block main %}
		<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="Submit" value="Sign In">
	</form>
	<p> هنوز <a href='{% url "accounts:sign_up" %}'> ثبت نام </a> نکردی؟! </p>
{% endblock %}

templates/accounts/sign_up.html
{% extends 'home/base.html' %}

{% block title %}
	<title>ثبت نام</title>
{% endblock %}

{% block main %}
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="Submit" value="Sign In">
	</form>
{% endblock %}

templates/credit/increase_user_credit.html
{% extends 'home/base.html' %}


{% block title %}
<title>افزایش موجودی</title>
{% endblock %}



{% block main %}

<form method="POST">
	{% csrf_token %}

	{{ form.as_p }}

	<input type="submit" name="Submit">
</form>

{% endblock %}

templates/credit/show_user_credit.html
{% extends 'home/base.html' %}

{% block title %}
<title>موجودی</title>
{% endblock %}


{% block main %}

 
	<h1>{{user_credit.amount_credit}}</h1>
	<a href="{% url 'credit:increase_user_credit' %}"> افزایش موجودی </a>

{% endblock %}

templates/home/base.html
{% load static %}

<!doctype html>
<html dir="rtl" lang="">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    {% block title %}
    {% endblock %}
    

    

	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-DOXMLfHhQkvFFp+rWTZwVlPVqdIhpDVYT9csOnHSgWQWPX0v5MCGtjCJbY6ERspU" crossorigin="anonymous">

    <style>
        /* Modify the background color */
         
        .navbar-custom {
            background-color: #0B0C10;
        }
        /* Modify brand and text color */
         
        .navbar-custom .navbar-brand,
        .navbar-custom .navbar-text {
            color: #66FCF1;
        }
        .body{
          background-color: #1F2833;
          color: #C5C6C7;
        }
        .body .h1{
          color: #66FCF1 ;
        }

    </style>    
  </head>
  <body class="body">
  	<header>
  		<nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
  <a class="navbar-brand mb-1" href="{% url 'home:home' %}">فرید</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link navbar-text active" href="{% url 'home:home' %}">خانه</a>
      {% if not user.is_authenticated %}
      <a class="nav-item nav-link active" href="{% url 'accounts:sign_in' %}">وارد شوید </a>
      {% endif %}
      {% if user.is_authenticated %}
      <a class="nav-item nav-link active" href="{% url 'sonicresult:search_form' %}"> جست و جو </a>
      <ul class="navbar-nav  ">
      	<li class="nav-item dropdown">
      		<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle='dropdown' aria-haspopup="true" aria-expanded="false" href="Toggle">حساب کاربری
      		</a>
      		<div class="dropdown-menu" aria-labelledby="navbarDropdown">
          		<a class="dropdown-item" href="{% url 'credit:show_user_credit' %}">افزایش موجودی</a>
          		<a class="dropdown-item" href="{% url 'accounts:sign_out' %}">خروج</a>
        	</div>
      	</li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>
  	</header>
    <main>
    {% block main %}
    {% endblock %}
  </main>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

      
  </body>
</html>

templates/home/index.html
{% extends 'home/base.html' %}

{% block title %}
	<title>خانه</title>
{% endblock %}


{% block main %}
	<div class="container-fluid">
		<h1 class="h1 p-3"> به اینجا خوش آمدید! </h1>
		<h4> برای استفاده از سایت ابتدا <a href="{% url 'accounts:sign_in' %}"> وارد شوید</a>. </h4>
	</div>

{% endblock %}

templates/sonicresult/result.html
{% extends 'home/base.html' %}


{% block title %}
    <title>پاسخ</title>
{% endblock %}


{% block main %}
    <h4>{{result.from_ai}}</h4>

{% endblock %}

templates/sonicresult/search_article.html
{% extends 'home/base.html' %}


{% block title %}
    <title>پرسش</title>
{% endblock %}



{% block main %}
    <form method="POST" >
        {% csrf_token %}
        <p>Text</p>
        <textarea name ='to_ai'></textarea>
        <input type="submit" name="Submit">

    </form>
{% endblock %}